/*
 * This file is generated by jOOQ.
 */
package org.scytec.interview.db.model.tables;


import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.scytec.interview.db.model.Keys;
import org.scytec.interview.db.model.Public;
import org.scytec.interview.db.model.tables.records.ClanRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Clan extends TableImpl<ClanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.CLAN</code>
     */
    public static final Clan CLAN = new Clan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClanRecord> getRecordType() {
        return ClanRecord.class;
    }

    /**
     * The column <code>PUBLIC.CLAN.ID</code>.
     */
    public final TableField<ClanRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.CLAN.NAME</code>.
     */
    public final TableField<ClanRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(1000000000), this, "");

    /**
     * The column <code>PUBLIC.CLAN.GOLD</code>.
     */
    public final TableField<ClanRecord, Integer> GOLD = createField(DSL.name("GOLD"), SQLDataType.INTEGER, this, "");

    private Clan(Name alias, Table<ClanRecord> aliased) {
        this(alias, aliased, null);
    }

    private Clan(Name alias, Table<ClanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PUBLIC.CLAN</code> table reference
     */
    public Clan(String alias) {
        this(DSL.name(alias), CLAN);
    }

    /**
     * Create an aliased <code>PUBLIC.CLAN</code> table reference
     */
    public Clan(Name alias) {
        this(alias, CLAN);
    }

    /**
     * Create a <code>PUBLIC.CLAN</code> table reference
     */
    public Clan() {
        this(DSL.name("CLAN"), null);
    }

    public <O extends Record> Clan(Table<O> child, ForeignKey<O, ClanRecord> key) {
        super(child, key, CLAN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ClanRecord, Long> getIdentity() {
        return (Identity<ClanRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ClanRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_1;
    }

    @Override
    public Clan as(String alias) {
        return new Clan(DSL.name(alias), this);
    }

    @Override
    public Clan as(Name alias) {
        return new Clan(alias, this);
    }

    @Override
    public Clan as(Table<?> alias) {
        return new Clan(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Clan rename(String name) {
        return new Clan(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clan rename(Name name) {
        return new Clan(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clan rename(Table<?> name) {
        return new Clan(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super String, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
