/*
 * This file is generated by jOOQ.
 */
package org.scytec.interview.db.model.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.scytec.interview.db.model.tables.ClanHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanHistoryRecord extends UpdatableRecordImpl<ClanHistoryRecord> implements Record8<Long, LocalDateTime, String, Long, Long, Long, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.DATE_TIME</code>.
     */
    public void setDateTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.DATE_TIME</code>.
     */
    public LocalDateTime getDateTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.ACTION</code>.
     */
    public void setAction(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.ACTION</code>.
     */
    public String getAction() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.CLAN_ID</code>.
     */
    public void setClanId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.CLAN_ID</code>.
     */
    public Long getClanId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.USER_ID</code>.
     */
    public void setUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.USER_ID</code>.
     */
    public Long getUserId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.TASK_ID</code>.
     */
    public void setTaskId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.TASK_ID</code>.
     */
    public Long getTaskId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.GOLD_FROM</code>.
     */
    public void setGoldFrom(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.GOLD_FROM</code>.
     */
    public Integer getGoldFrom() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>PUBLIC.CLAN_HISTORY.GOLD_TO</code>.
     */
    public void setGoldTo(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.CLAN_HISTORY.GOLD_TO</code>.
     */
    public Integer getGoldTo() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, LocalDateTime, String, Long, Long, Long, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, LocalDateTime, String, Long, Long, Long, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ClanHistory.CLAN_HISTORY.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ClanHistory.CLAN_HISTORY.DATE_TIME;
    }

    @Override
    public Field<String> field3() {
        return ClanHistory.CLAN_HISTORY.ACTION;
    }

    @Override
    public Field<Long> field4() {
        return ClanHistory.CLAN_HISTORY.CLAN_ID;
    }

    @Override
    public Field<Long> field5() {
        return ClanHistory.CLAN_HISTORY.USER_ID;
    }

    @Override
    public Field<Long> field6() {
        return ClanHistory.CLAN_HISTORY.TASK_ID;
    }

    @Override
    public Field<Integer> field7() {
        return ClanHistory.CLAN_HISTORY.GOLD_FROM;
    }

    @Override
    public Field<Integer> field8() {
        return ClanHistory.CLAN_HISTORY.GOLD_TO;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getDateTime();
    }

    @Override
    public String component3() {
        return getAction();
    }

    @Override
    public Long component4() {
        return getClanId();
    }

    @Override
    public Long component5() {
        return getUserId();
    }

    @Override
    public Long component6() {
        return getTaskId();
    }

    @Override
    public Integer component7() {
        return getGoldFrom();
    }

    @Override
    public Integer component8() {
        return getGoldTo();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getDateTime();
    }

    @Override
    public String value3() {
        return getAction();
    }

    @Override
    public Long value4() {
        return getClanId();
    }

    @Override
    public Long value5() {
        return getUserId();
    }

    @Override
    public Long value6() {
        return getTaskId();
    }

    @Override
    public Integer value7() {
        return getGoldFrom();
    }

    @Override
    public Integer value8() {
        return getGoldTo();
    }

    @Override
    public ClanHistoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ClanHistoryRecord value2(LocalDateTime value) {
        setDateTime(value);
        return this;
    }

    @Override
    public ClanHistoryRecord value3(String value) {
        setAction(value);
        return this;
    }

    @Override
    public ClanHistoryRecord value4(Long value) {
        setClanId(value);
        return this;
    }

    @Override
    public ClanHistoryRecord value5(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public ClanHistoryRecord value6(Long value) {
        setTaskId(value);
        return this;
    }

    @Override
    public ClanHistoryRecord value7(Integer value) {
        setGoldFrom(value);
        return this;
    }

    @Override
    public ClanHistoryRecord value8(Integer value) {
        setGoldTo(value);
        return this;
    }

    @Override
    public ClanHistoryRecord values(Long value1, LocalDateTime value2, String value3, Long value4, Long value5, Long value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClanHistoryRecord
     */
    public ClanHistoryRecord() {
        super(ClanHistory.CLAN_HISTORY);
    }

    /**
     * Create a detached, initialised ClanHistoryRecord
     */
    public ClanHistoryRecord(Long id, LocalDateTime dateTime, String action, Long clanId, Long userId, Long taskId, Integer goldFrom, Integer goldTo) {
        super(ClanHistory.CLAN_HISTORY);

        setId(id);
        setDateTime(dateTime);
        setAction(action);
        setClanId(clanId);
        setUserId(userId);
        setTaskId(taskId);
        setGoldFrom(goldFrom);
        setGoldTo(goldTo);
    }
}
