/*
 * This file is generated by jOOQ.
 */
package org.scytec.interview.db.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.scytec.interview.db.model.tables.UserProfile;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> implements Record3<Long, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PUBLIC.USER_PROFILE.ID</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_PROFILE.ID</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>PUBLIC.USER_PROFILE.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_PROFILE.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.USER_PROFILE.GOLD</code>.
     */
    public void setGold(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.USER_PROFILE.GOLD</code>.
     */
    public Integer getGold() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserProfile.USER_PROFILE.ID;
    }

    @Override
    public Field<String> field2() {
        return UserProfile.USER_PROFILE.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return UserProfile.USER_PROFILE.GOLD;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getGold();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getGold();
    }

    @Override
    public UserProfileRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserProfileRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserProfileRecord value3(Integer value) {
        setGold(value);
        return this;
    }

    @Override
    public UserProfileRecord values(Long value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(Long id, String name, Integer gold) {
        super(UserProfile.USER_PROFILE);

        setId(id);
        setName(name);
        setGold(gold);
    }
}
