/*
 * This file is generated by jOOQ.
 */
package org.scytec.interview.db.model;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.scytec.interview.db.model.tables.Clan;
import org.scytec.interview.db.model.tables.ClanHistory;
import org.scytec.interview.db.model.tables.Task;
import org.scytec.interview.db.model.tables.UserProfile;
import org.scytec.interview.db.model.tables.records.ClanHistoryRecord;
import org.scytec.interview.db.model.tables.records.ClanRecord;
import org.scytec.interview.db.model.tables.records.TaskRecord;
import org.scytec.interview.db.model.tables.records.UserProfileRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClanRecord> CONSTRAINT_1 = Internal.createUniqueKey(Clan.CLAN, DSL.name("CONSTRAINT_1"), new TableField[] { Clan.CLAN.ID }, true);
    public static final UniqueKey<ClanHistoryRecord> CONSTRAINT_5 = Internal.createUniqueKey(ClanHistory.CLAN_HISTORY, DSL.name("CONSTRAINT_5"), new TableField[] { ClanHistory.CLAN_HISTORY.ID }, true);
    public static final UniqueKey<TaskRecord> CONSTRAINT_2 = Internal.createUniqueKey(Task.TASK, DSL.name("CONSTRAINT_2"), new TableField[] { Task.TASK.ID }, true);
    public static final UniqueKey<UserProfileRecord> CONSTRAINT_C = Internal.createUniqueKey(UserProfile.USER_PROFILE, DSL.name("CONSTRAINT_C"), new TableField[] { UserProfile.USER_PROFILE.ID }, true);
}
