/*
 * This file is generated by jOOQ.
 */
package org.scytec.interview.db.model;


import org.scytec.interview.db.model.tables.Clan;
import org.scytec.interview.db.model.tables.ClanHistory;
import org.scytec.interview.db.model.tables.Task;
import org.scytec.interview.db.model.tables.UserProfile;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.CLAN</code>.
     */
    public static final Clan CLAN = Clan.CLAN;

    /**
     * The table <code>PUBLIC.CLAN_HISTORY</code>.
     */
    public static final ClanHistory CLAN_HISTORY = ClanHistory.CLAN_HISTORY;

    /**
     * The table <code>PUBLIC.TASK</code>.
     */
    public static final Task TASK = Task.TASK;

    /**
     * The table <code>PUBLIC.USER_PROFILE</code>.
     */
    public static final UserProfile USER_PROFILE = UserProfile.USER_PROFILE;
}
